### ISSUE TITLE
Single end data, with a custom bowtie2 index results in 'missing index' error, but paired end data works fine

### ISSUE THREAD

**Issue by jfy133** [bede/hostile#46]
I'm currently creating an [nf-core](https://nf-co.re/modules) Nextflow module for `hostile clean`.

I've come across a slightly strange behaviour when setting up the tests for the module.

For the tests I'm doing a slight nonsense test to make tests fast by using a tiny genome (SARS-CoV2) as the host reference to align against rather than the standard Hostile references.

I have run `bowtie-build` on the tiny genome to generate the indicies (Without masking, but if I understand correctly this isn't required anyway).

When I run `hostile clean` with paired-end FASTQ files (of a SARS-Cov2 sample) , the command works fine and produces valid empty (well empty FASTQ files, but there is no error and I get the JSON stats).

When I run the same command but with just a single-end data (I literally just remove the `--fastq2 <file>`), suddenly `hostile clean` errors with an error:

```
FileNotFoundError: bowtie2/genome is neither a valid custom index path nor a valid standard index name. Disable offline mode to enable discovery of standard indexes
```

I'm guessing this is a wierd bug of some kind?

I've packaged up my test files in the following file:

[hostile_bug.tar.gz](https://github.com/user-attachments/files/17674770/hostile_bug.tar.gz)

To replicate:

- I installed hostile via bioconda (hostile v1.1.0)
- Run `bash command_pe.sh` to test paired end data (this should work)
- `rm -r cleaned_reads` to manually remove the outdir (I know I could use `--force`, but the nf-core module shouldn't encounter this)
- Run `bash command_pe.sh` to test single end data (this should fail)

**Comment by bede** [comment]
Hi James,
Thank you so much for seeking to create a nextflow module! I'm sorry for not replying sooner and naturally want to support this in any way I can.

The good news is that this is expected behaviour. When only `--fastq1` is provided, Hostile defaults to long read mode using Minimap2. When both `--fastq1` and `--fastq2` are specified, Hostile defaults to short read mode (Bowtie2). In either case the default can be overridden using the `--aligner` argument with values of either `bowtie2` or `minimap2`. In your SE test case you are passing a Bowtie2 index to Hostile operating in Minimap2 mode, where it expects a genome in FASTA format.

Although intended, I agree that this is potentially confusing. I made the CLI work this way to ensure that the appropriate aligner is used for short and long reads by default. I'll see if I can better communicate this behaviour in the README. Adding some more detail to the Exception message might help also I think. Suggestions welcome.

Thanks for bundling your tests. In the SE case all you should do is provide the FASTA genome, e.g. `--index MN908947.fasta` rather than the Bowtie2 index path and it should work as expected. Unfortunately when working with custom indexes the user is exposed to the complexity of the different index formats.

I also use the SARS-CoV-2 genome for test cases as it happens:
https://github.com/bede/hostile/blob/main/tests/test_all.py

Please reach out (here or directly) if you run into any more difficulties and I'll try to respond more promptly.

**Comment by jfy133** [comment]
Hi @bede !

This is very helpful!

Ah, you are indeed correct, when looking at the `clean --help` message:

```
  --aligner {bowtie2,minimap2,auto}
                        alignment algorithm. Default is Bowtie2 (paired reads) & Minimap2 (unpaired reads)
                        (default: auto)
```

I guess I must have missed that as in my area the terminolgy is `paired` and `single-end` where `unpaired` refers to paired-end sequenced libraries, where for some reads in that library one  pair has been removed due low-quality or trimming etc.  So as I didn't see the 'single-end' keyword my brain didn't read it properly.

And indeed reading the README you definitely do state this under 'Short unpaired reads, save log' [section](Short unpaired reads, save log). - probably again due to my terminology assumption

So inconclusion I didn't RTFM properly :sweat: but I think indeed slightly more explicit documentation in `--help` would help here.

I personally wouldn't make the assumption that a single FASTQ is long reads - could also be merged reads (for whatever reason), or single-end sequenced libraries data. But this is just me and I come out of a slightly unusual genetics background (aDNA where everything is always short).

From PoV my suggestions to maybe improve a user experience here would be:

- Clarify a bit more in the `--help` that this is required
- Specify across all documentation 'unpaired or single-end` FASTQs
- Maybe add an error message suggestion that if `--fastq` is given but the `--index` doesn't contains `.mmi` give a suggestion 'Did you supply the correct index? Single-end/unpaired short read FASTQs should specify --bowite2!' or something

**Comment by jfy133** [comment]
Will close as per the better enhancement request as above

**Comment by bede** [comment]
Thanks for explaining – your interpretation of unpaired is quite understandable.

I'm wary of changing default behaviour for fastq1 (defaults to long read) vs fastq1 && fastq2 (defaults to short read), but we can make things clearer in CLI help and usage guidlines and I've opened a couple of to do items as you've seen.

Thanks for feedback
