### ISSUE TITLE
add mm39 genome index?

### ISSUE THREAD

**Issue by microbemarsh** [bede/hostile#49]
Hi @bede,

Great work on hostile, its very user friendly and nice for human microbiome research, however my group does some mouse microbiome research and I was wondering if you had thought about adding any other additional indexes to the list. I saw you're looking to do a new release soon and wanted to add my two cents!

Thanks,
Austin

**Comment by bede** [comment]
Hi Austin,
Thanks for your message. Are you aware that you can supply custom indexes already? If dehosting long reads you can provide a path to a fasta file instead of an index name. For short reads you'll need to build a bowtie2 index, e.g. `bowtie2-build genome.fa index-name` which can be referenced in similar fashion (see README for details). Would you specifically like to see a standard (prebuilt) Hostile index for mouse available in object storage? I appreciate that this is more convenient and can consider adding it. 

Thanks,
Bede

**Comment by microbemarsh** [comment]
In the case of using a custom index on long reads, is it essentially just finding the alignments with minimap2 and removing those regions from the output fastq? And it might be useful to users later on to have the prebuilt mouse index available but if I'm the first to request it I would say its not too pertinent to add it.

**Comment by bede** [comment]
Thanks, yes, the approach is to stream SAM alignments, count distinct records (reads in), discard reads that align well or have a mate pair that aligns well, count remaining (reads out), optionally rename and reorder reads, and then write remaining reads back to compressed fastq. You can see what's happening if you include the `--debug` option when running `hostile clean`.

I'll add an mm39 index in the next day or two – please let me know if you have any more advice. I plan to use `GCF_000001635.27_GRCm39_genomic.fna` from https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001635.27/ and name the index `mouse-mm39`.

**Comment by bede** [comment]
Hi Austin,
I've added mm39 so that it can automatically fetched and cached when referenced by name (`hostile clean --index mouse-mm39`). You can also prefetch both short and long read indexes with `hostile fetch --name mouse-mm39`.

I briefly looked at decontamination performance with a couple of short read mouse FASTQs and saw 97-98% depletion, in line with what I'd expect for a reference genome with this level of completeness. Thanks for the suggestion!

**Comment by microbemarsh** [comment]
Hi @bede 

Wow, thank you for doing this so quickly. I look forward to implementing this in our metagenomics pipeline!
